template_path: beanstalk-extras.yaml
stack_name: agora-develop-extras
dependencies:
  - develop/agora.yaml
parameters:
  ListenerArn: "arn:aws:elasticloadbalancing:us-east-1:055273631518:listener/app/awseb-AWSEB-R8AL4TAACN8K/f1f0223eb67f6f12/c8698afff25350af"
  CertificateArn: "arn:aws:acm:us-east-1:055273631518:certificate/412c0ea4-8123-48dd-b0af-608558cbb902"   # *.ampadportal.org
