template_path: alb-redirector.yaml
stack_name: agora-dev-alb-redirector
dependencies:
  - develop/agora.yaml
parameters:
  ListenerArn: "arn:aws:elasticloadbalancing:us-east-1:055273631518:listener/app/awseb-AWSEB-R8AL4TAACN8K/f1f0223eb67f6f12/c8698afff25350af"
  RedirectFromHost: "agora-develop.ampadportal.org"
  RedirectToHost: "agora-develop.adknowledgeportal.org"
